import { User, Product, Category, Order, Address, ProductReview, CartItem } from '../../frontend/src/types';

// Seed Categories
export const initialCategories: Category[] = [
  {
    id: 'cat-women-ethnic',
    name: 'Women Ethnic',
    nameHindi: 'महिला एथनिक',
    slug: 'women-ethnic',
    icon: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    description: 'Sarees, Kurtis, Anarkali Sets & Lehengas directly from weavers',
  },
  {
    id: 'cat-western',
    name: 'Western Wear',
    nameHindi: 'वेस्टर्न वियर',
    slug: 'western-wear',
    icon: 'Shirt',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
    description: 'Trendy tops, dresses, coords, denim & casuals',
  },
  {
    id: 'cat-mens-fashion',
    name: "Men's Fashion",
    nameHindi: 'पुरुष फैशन',
    slug: 'mens-fashion',
    icon: 'UserCheck',
    imageUrl: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=600&auto=format&fit=crop&q=80',
    description: 'Ethnic kurtas, printed shirts, jeans & lounge wear',
  },
  {
    id: 'cat-jewellery',
    name: 'Jewellery & Watches',
    nameHindi: 'ज्वेलरी व घड़ियां',
    slug: 'jewellery',
    icon: 'Gem',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    description: 'Traditional Jhumkas, Kundan sets, oxidized pieces & bangles',
  },
  {
    id: 'cat-home-kitchen',
    name: 'Home & Kitchen',
    nameHindi: 'होम और किचन',
    slug: 'home-kitchen',
    icon: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    description: 'Bedsheets, curtains, kitchen organizers & brass decor',
  },
  {
    id: 'cat-beauty',
    name: 'Beauty & Wellness',
    nameHindi: 'ब्यूटी व स्किनकेयर',
    slug: 'beauty',
    icon: 'HeartHandshake',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&auto=format&fit=crop&q=80',
    description: 'Herbal haircare, kajal, lipsticks, and skin glow serums',
  },
  {
    id: 'cat-kids',
    name: 'Kids & Baby',
    nameHindi: 'बच्चों के कपड़े',
    slug: 'kids-baby',
    icon: 'Smile',
    imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&auto=format&fit=crop&q=80',
    description: 'Cute dresses, ethnic sets for festivals & soft cotton basics',
  },
];

// Seed Users
export const initialUsers: User[] = [
  {
    id: 'user-priya',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '9876543210',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    city: 'Jaipur',
    state: 'Rajasthan',
    createdAt: '2025-01-15T10:00:00.000Z',
  },
  {
    id: 'user-seller-ramesh',
    name: 'Ramesh Handlooms & Weaves',
    email: 'seller@example.com',
    phone: '9820011223',
    role: 'seller',
    businessName: 'Surat Fab Hub Wholesale',
    city: 'Surat',
    state: 'Gujarat',
    createdAt: '2024-11-01T09:00:00.000Z',
  },
  {
    id: 'user-admin',
    name: 'Shopzy Administrator',
    email: 'admin@shopzy.in',
    phone: '9999988888',
    role: 'admin',
    city: 'Bengaluru',
    state: 'Karnataka',
    createdAt: '2024-01-01T00:00:00.000Z',
  },
];

// Seed Addresses for customer
export const initialAddresses: Address[] = [
  {
    id: 'addr-1',
    userId: 'user-priya',
    name: 'Priya Sharma',
    phone: '9876543210',
    street: 'Flat 402, Royal Residency, Near City Palace Road',
    area: 'C-Scheme',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302001',
    isDefault: true,
    type: 'home',
  },
  {
    id: 'addr-2',
    userId: 'user-priya',
    name: 'Sunita Meena (Resell Customer)',
    phone: '9811122334',
    street: 'House No. 12, Malviya Nagar Sector 4',
    area: 'Malviya Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302017',
    isDefault: false,
    type: 'reseller_customer',
  },
];

// Seed Products
export const initialProducts: Product[] = [
  {
    id: 'prod-kurti-black-wedding',
    title: 'Georgette Embroidered Anarkali Kurti with Dupatta',
    titleHindi: 'जॉर्जेट कढ़ाई अनारकली कुर्ती व दुपट्टा (वेडिंग स्पेशल)',
    description: 'Heavy thread work festive Anarkali kurti in rich black with sequin highlights and matching net dupatta. Ideal for weddings, sangeet, and festive celebrations.',
    category: 'Women Ethnic',
    subCategory: 'Anarkali & Kurtis',
    price: 749,
    originalPrice: 2299,
    discountPercent: 67,
    rating: 4.6,
    ratingCount: 1420,
    reviewCount: 388,
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 45,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Jaipur Fab Hub Wholesale',
    sellerCity: 'Jaipur',
    freeDelivery: true,
    colors: ['Black', 'Maroon', 'Navy Blue'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    fabric: 'Georgette',
    returnDays: 7,
    codAvailable: true,
    tags: ['wedding', 'kurti', 'black', 'anarkali', 'festive', 'dupatta', 'partywear'],
    isFeatured: true,
    isTrending: true,
    reviews: [
      {
        id: 'rev-1',
        userId: 'user-101',
        userName: 'Aarti Verma',
        rating: 5,
        comment: 'Wedding ke liye mangwayi thi, quality is top notch! Black colour bohot hi royal lagta hai.',
        date: '2025-02-14',
        verifiedPurchase: true,
        helpfulCount: 42,
        customerCity: 'Lucknow',
      },
      {
        id: 'rev-2',
        userId: 'user-102',
        userName: 'Meenakshi Iyer',
        rating: 4,
        comment: 'Worth the price! Under 800 it is a steal deal for wedding functions.',
        date: '2025-02-18',
        verifiedPurchase: true,
        helpfulCount: 18,
        customerCity: 'Delhi',
      },
    ],
  },
  {
    id: 'prod-kurti-maroon-budget',
    title: 'Floral Printed Rayon Straight Kurti (Everyday Festive)',
    titleHindi: 'फ्लोरल प्रिंटेड रेयॉन स्ट्रेट कुर्ती',
    description: 'Pure 140 GSM breathable rayon straight kurti with gota patti detailing on neckline. Budget-friendly alternative for festive functions.',
    category: 'Women Ethnic',
    subCategory: 'Anarkali & Kurtis',
    price: 399,
    originalPrice: 1299,
    discountPercent: 69,
    rating: 4.3,
    ratingCount: 890,
    reviewCount: 145,
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 80,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Jaipur Fab Hub Wholesale',
    sellerCity: 'Surat',
    freeDelivery: true,
    colors: ['Maroon', 'Black', 'Mustard Yellow'],
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Rayon',
    returnDays: 7,
    codAvailable: true,
    tags: ['kurti', 'cheap', 'budget', 'similar', 'wedding', 'rayon', 'maroon', 'black'],
    isFeatured: true,
    isTrending: false,
    reviews: [
      {
        id: 'rev-3',
        userId: 'user-103',
        userName: 'Pooja Tiwari',
        rating: 5,
        comment: 'Cheaper alternative to heavy kurtis, daily aur pooja ke liye perfect!',
        date: '2025-02-20',
        verifiedPurchase: true,
        helpfulCount: 12,
        customerCity: 'Varanasi',
      },
    ],
  },
  {
    id: 'prod-saree-banarasi-silk',
    title: 'Varanasi Jacquard Zari Woven Kanjivaram Silk Saree',
    titleHindi: 'बनारसी जरी वोवन सॉफ्ट सिल्क साड़ी ब्लाउज पीस के साथ',
    description: 'Authentic Banarasi soft silk saree with heavy zari pallu and rich temple floral border. Includes unstitched brocade blouse piece.',
    category: 'Women Ethnic',
    subCategory: 'Sarees',
    price: 899,
    originalPrice: 3499,
    discountPercent: 74,
    rating: 4.7,
    ratingCount: 2310,
    reviewCount: 520,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 60,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Kalyan Handlooms',
    sellerCity: 'Varanasi',
    freeDelivery: true,
    colors: ['Emerald Green', 'Royal Red', 'Peacock Blue'],
    sizes: ['Free Size (5.5m + 0.8m Blouse)'],
    fabric: 'Banarasi Soft Silk',
    returnDays: 7,
    codAvailable: true,
    tags: ['saree', 'silk', 'banarasi', 'wedding', 'festive', 'zari', 'traditional'],
    isFeatured: true,
    isTrending: true,
    reviews: [
      {
        id: 'rev-4',
        userName: 'Kavita Joshi',
        userId: 'user-104',
        rating: 5,
        comment: 'Bohot sundar saree hai, relatives thought I bought it for 4000 rupees!',
        date: '2025-01-29',
        verifiedPurchase: true,
        helpfulCount: 64,
        customerCity: 'Ahmedabad',
      },
    ],
  },
  {
    id: 'prod-mens-kurta-chikankari',
    title: "Men's Lucknowi Chikankari Cotton Kurta & Pyjama Set",
    titleHindi: 'मेन्स लखनवी चिकनकारी कॉटन कुर्ता पजामा सेट',
    description: 'Handcrafted Lucknowi Chikan work on soft breathable cotton fabric with Mandarin collar. Perfect for pooja, weddings, and haldi functions.',
    category: "Men's Fashion",
    subCategory: 'Ethnic Wear',
    price: 649,
    originalPrice: 1999,
    discountPercent: 67,
    rating: 4.5,
    ratingCount: 780,
    reviewCount: 210,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 35,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Awadh Textile House',
    sellerCity: 'Lucknow',
    freeDelivery: true,
    colors: ['White', 'Pastel Yellow', 'Powder Blue'],
    sizes: ['M (38)', 'L (40)', 'XL (42)', 'XXL (44)'],
    fabric: 'Pure Cotton',
    returnDays: 7,
    codAvailable: true,
    tags: ['mens', 'kurta', 'chikankari', 'wedding', 'haldi', 'ethnic', 'white'],
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'prod-oxidised-jhumka-set',
    title: 'Afghan Tribal Mirror Work Oxidised Jhumka Earrings',
    titleHindi: 'ट्राइबल मिरर वर्क ऑक्सीडाइज्ड झुमका',
    description: 'Lightweight german silver finish oxidised long jhumkas with ghungroo bells and sparkling mirror work.',
    category: 'Jewellery & Watches',
    subCategory: 'Earrings & Sets',
    price: 199,
    originalPrice: 699,
    discountPercent: 71,
    rating: 4.8,
    ratingCount: 3400,
    reviewCount: 890,
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 120,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Johari Bazar Jewelers',
    sellerCity: 'Jaipur',
    freeDelivery: true,
    colors: ['Silver', 'Antique Black Silver'],
    sizes: ['Standard'],
    fabric: 'Alloy',
    returnDays: 7,
    codAvailable: true,
    tags: ['jewellery', 'jhumka', 'earrings', 'oxidised', 'mirror', 'cheap', 'under 200'],
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'prod-bedsheet-cotton-king',
    title: '100% Pure Cotton King Size Bedsheet with 2 Pillow Covers',
    titleHindi: '100% प्योर कॉटन किंग साइज चादर व 2 तकिया कवर',
    description: '210 TC breathable sateen weave cotton double bedsheet with traditional Jaipuri floral block prints. Colorfast guarantee.',
    category: 'Home & Kitchen',
    subCategory: 'Bedding',
    price: 499,
    originalPrice: 1599,
    discountPercent: 68,
    rating: 4.6,
    ratingCount: 1650,
    reviewCount: 420,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 55,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Sanganer Print Mills',
    sellerCity: 'Jaipur',
    freeDelivery: true,
    colors: ['Indigo Blue', 'Maroon Paisley', 'Pastel Floral'],
    sizes: ['King Size (108x108 inch)'],
    fabric: 'Pure Cotton',
    returnDays: 7,
    codAvailable: true,
    tags: ['bedsheet', 'cotton', 'home', 'bedroom', 'jaipuri', 'double bed'],
    isFeatured: false,
    isTrending: true,
  },
  {
    id: 'prod-dress-western-floral',
    title: 'A-Line Georgette Tiered Midi Dress with Belt',
    titleHindi: 'ए-लाइन फ्लोरल टियर्ड मिडी ड्रेस बेल्ट के साथ',
    description: 'Breezy knee-length floral print summer dress with sweetheart neckline and smocked back for comfortable fit.',
    category: 'Western Wear',
    subCategory: 'Dresses',
    price: 449,
    originalPrice: 1499,
    discountPercent: 70,
    rating: 4.4,
    ratingCount: 920,
    reviewCount: 230,
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 40,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Ludhiana Fast Fashion Co.',
    sellerCity: 'Ludhiana',
    freeDelivery: true,
    colors: ['Lilac Floral', 'Black Daisy', 'Sage Green'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    fabric: 'Georgette',
    returnDays: 7,
    codAvailable: true,
    tags: ['dress', 'western', 'floral', 'midi', 'casual', 'party'],
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'prod-beauty-matte-lipstick-combo',
    title: '12-Hour Waterproof Non-Transfer Liquid Lipstick Combo (Pack of 3)',
    titleHindi: '12 घंटे वॉटरप्रूफ मैट लिक्विड लिपस्टिक (3 का पैक)',
    description: 'Vitamin E enriched transfer-proof matte shades suitable for all Indian skin tones: Nude Peach, Berry Red, and Deep Plum.',
    category: 'Beauty & Wellness',
    subCategory: 'Makeup',
    price: 279,
    originalPrice: 899,
    discountPercent: 69,
    rating: 4.5,
    ratingCount: 4200,
    reviewCount: 1100,
    images: [
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 200,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Naturals Herbal Beauty',
    sellerCity: 'Mumbai',
    freeDelivery: true,
    colors: ['Nude Trio Pack', 'Festive Reds Pack'],
    sizes: ['Pack of 3'],
    fabric: 'Cosmetic',
    returnDays: 7,
    codAvailable: true,
    tags: ['beauty', 'lipstick', 'matte', 'makeup', 'combo', 'waterproof', 'under 300'],
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'prod-kids-ethnic-dhoti-kurta',
    title: "Boys Festive Silk Jacquard Kurta with Dhoti Set",
    titleHindi: 'बॉयज फेस्टिव सिल्क जैक्वार्ड कुर्ता धोती सेट',
    description: 'Comfortable elasticated dhoti pants with brocade woven kurta for festivals, diwali, and family weddings.',
    category: 'Kids & Baby',
    subCategory: 'Boys Ethnic',
    price: 499,
    originalPrice: 1499,
    discountPercent: 66,
    rating: 4.6,
    ratingCount: 540,
    reviewCount: 120,
    images: [
      'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 30,
    sellerId: 'user-seller-ramesh',
    sellerName: 'TinyTots Apparel',
    sellerCity: 'Surat',
    freeDelivery: true,
    colors: ['Maroon Gold', 'Royal Blue Gold'],
    sizes: ['2-3 Yrs', '4-5 Yrs', '6-7 Yrs', '8-9 Yrs'],
    fabric: 'Art Silk',
    returnDays: 7,
    codAvailable: true,
    tags: ['kids', 'dhoti', 'kurta', 'boys', 'festive', 'ethnic'],
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'prod-kitchen-chopper-manual',
    title: 'Quick 6-Blade Stainless Steel Food Chopper & Whisk',
    titleHindi: 'क्विक 6-ब्लेड फूड चॉपर और व्हिस्कर',
    description: 'Effortlessly chop onions, tomatoes, dry fruits with easy pull cord mechanism. Unbreakable ABS body.',
    category: 'Home & Kitchen',
    subCategory: 'Kitchen Tools',
    price: 249,
    originalPrice: 799,
    discountPercent: 68,
    rating: 4.7,
    ratingCount: 5800,
    reviewCount: 1420,
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 150,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Smart Kitchen Mart',
    sellerCity: 'Rajkot',
    freeDelivery: true,
    colors: ['Green', 'Grey', 'Aqua Blue'],
    sizes: ['900 ml'],
    fabric: 'BPA-Free Plastic',
    returnDays: 7,
    codAvailable: true,
    tags: ['kitchen', 'chopper', 'home', 'useful', 'under 300', 'tools'],
    isFeatured: false,
    isTrending: true,
  },
  {
    id: 'prod-kurti-cotton-daily',
    title: 'Pure Cotton Printed A-line Daily Wear Kurti',
    titleHindi: 'प्योर कॉटन प्रिंटेड ए-लाइन डेली वियर कुर्ती',
    description: 'Simple and elegant cotton daily kurti with 3/4th sleeves. Super soft and sweat-absorbent for Indian weather.',
    category: 'Women Ethnic',
    subCategory: 'Anarkali & Kurtis',
    price: 299,
    originalPrice: 899,
    discountPercent: 66,
    rating: 4.4,
    ratingCount: 1200,
    reviewCount: 290,
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 90,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Jaipur Fab Hub Wholesale',
    sellerCity: 'Jaipur',
    freeDelivery: true,
    colors: ['Indigo', 'Yellow', 'Black'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    fabric: 'Cotton',
    returnDays: 7,
    codAvailable: true,
    tags: ['kurti', 'cotton', 'daily', 'cheap', 'budget', 'under 300'],
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'prod-kundan-necklace-set',
    title: 'Bridal Kundan & Pearl Choker Necklace with Matching Earrings & Maangtikka',
    titleHindi: 'कुंदन व पर्ल ब्राइडल चोकर सेट (ईयररिंग्स व मांगटीका सहित)',
    description: 'Exquisite handcrafted bridal choker necklace set featuring high-shine stones and mint green cluster beads.',
    category: 'Jewellery & Watches',
    subCategory: 'Earrings & Sets',
    price: 699,
    originalPrice: 2499,
    discountPercent: 72,
    rating: 4.8,
    ratingCount: 1840,
    reviewCount: 460,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
    ],
    stock: 35,
    sellerId: 'user-seller-ramesh',
    sellerName: 'Johari Bazar Jewelers',
    sellerCity: 'Jaipur',
    freeDelivery: true,
    colors: ['Gold Mint', 'Gold Maroon', 'Gold White'],
    sizes: ['Adjustable Dori'],
    fabric: 'Brass Kundan',
    returnDays: 7,
    codAvailable: true,
    tags: ['jewellery', 'kundan', 'choker', 'necklace', 'wedding', 'bridal', 'maangtikka'],
    isFeatured: true,
    isTrending: true,
  }
];

// Pre-seeded Active Orders for Priya
export const initialOrders: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'SS-98214-IN',
    userId: 'user-priya',
    userName: 'Priya Sharma',
    userPhone: '9876543210',
    items: [
      {
        productId: 'prod-kurti-black-wedding',
        title: 'Georgette Embroidered Anarkali Kurti with Dupatta',
        image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
        price: 749,
        resellMargin: 150,
        finalCustomerPrice: 899,
        quantity: 1,
        color: 'Black',
        size: 'L',
        sellerName: 'Jaipur Fab Hub Wholesale',
      },
    ],
    shippingAddress: initialAddresses[0],
    paymentMethod: 'COD',
    paymentStatus: 'pending',
    subtotal: 749,
    discount: 0,
    shippingFee: 0,
    resellTotalMargin: 150,
    totalAmount: 899,
    status: 'in_transit',
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 48 * 3600 * 1000).toLocaleDateString('en-IN', {
      day: 'numeric',
      month: 'short',
      weekday: 'short',
    }),
    courierPartner: 'Delhivery Express',
    trackingNumber: 'DEL-IN-8834921',
    timeline: [
      {
        status: 'ordered',
        title: 'Order Placed & Verified',
        description: 'Order confirmed with Cash on Delivery',
        timestamp: new Date(Date.now() - 36 * 3600 * 1000).toLocaleString('en-IN'),
        location: 'Shopzy Jaipur Hub',
      },
      {
        status: 'packed',
        title: 'Quality Checked & Packed',
        description: 'Item checked by Jaipur Fab Hub quality team',
        timestamp: new Date(Date.now() - 24 * 3600 * 1000).toLocaleString('en-IN'),
        location: 'Jaipur Central Warehouse',
      },
      {
        status: 'shipped',
        title: 'Dispatched with Delhivery',
        description: 'AWB: DEL-IN-8834921 generated',
        timestamp: new Date(Date.now() - 16 * 3600 * 1000).toLocaleString('en-IN'),
        location: 'Jaipur Logistics Hub',
      },
      {
        status: 'in_transit',
        title: 'In Transit to Destination City',
        description: 'Arrived at Sort Center. Package moving on schedule.',
        timestamp: new Date(Date.now() - 4 * 3600 * 1000).toLocaleString('en-IN'),
        location: 'Jaipur North Sorting Facility',
      },
    ],
  },
  {
    id: 'ord-1002',
    orderNumber: 'SS-97451-IN',
    userId: 'user-priya',
    userName: 'Priya Sharma',
    userPhone: '9876543210',
    items: [
      {
        productId: 'prod-oxidised-jhumka-set',
        title: 'Afghan Tribal Mirror Work Oxidised Jhumka Earrings',
        image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
        price: 199,
        resellMargin: 0,
        finalCustomerPrice: 199,
        quantity: 1,
        color: 'Silver',
        size: 'Standard',
        sellerName: 'Johari Bazar Jewelers',
      },
    ],
    shippingAddress: initialAddresses[0],
    paymentMethod: 'UPI',
    paymentStatus: 'completed',
    subtotal: 199,
    discount: 0,
    shippingFee: 0,
    resellTotalMargin: 0,
    totalAmount: 199,
    status: 'delivered',
    createdAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
    estimatedDelivery: 'Delivered',
    courierPartner: 'Shadowfax Express',
    trackingNumber: 'SFX-9988210',
    timeline: [
      {
        status: 'ordered',
        title: 'Order Placed',
        description: 'Paid via UPI (PhonePe)',
        timestamp: new Date(Date.now() - 120 * 3600 * 1000).toLocaleString('en-IN'),
      },
      {
        status: 'shipped',
        title: 'Shipped',
        description: 'Dispatched from Jaipur',
        timestamp: new Date(Date.now() - 96 * 3600 * 1000).toLocaleString('en-IN'),
      },
      {
        status: 'delivered',
        title: 'Delivered Successfully',
        description: 'Delivered to recipient at C-Scheme, Jaipur',
        timestamp: new Date(Date.now() - 48 * 3600 * 1000).toLocaleString('en-IN'),
      },
    ],
  },
];

// In-Memory Database Store
class Database {
  users: User[] = [...initialUsers];
  categories: Category[] = [...initialCategories];
  products: Product[] = [...initialProducts];
  orders: Order[] = [...initialOrders];
  addresses: Address[] = [...initialAddresses];
  wishlists: Record<string, string[]> = {
    'user-priya': ['prod-kurti-black-wedding', 'prod-saree-banarasi-silk'],
  };
  carts: Record<string, CartItem[]> = {
    'user-priya': [
      {
        id: 'cart-init-1',
        productId: 'prod-oxidised-jhumka-set',
        product: initialProducts[4],
        quantity: 1,
        selectedColor: 'Silver',
        selectedSize: 'Standard',
        resellMargin: 50,
      },
    ],
  };

  // Helper finders
  findUserById(id: string) {
    return this.users.find((u) => u.id === id);
  }

  findUserByEmailOrPhone(query: string) {
    const q = query.trim().toLowerCase();
    return this.users.find((u) => u.email.toLowerCase() === q || u.phone === q);
  }

  findProductById(id: string) {
    return this.products.find((p) => p.id === id);
  }

  findOrdersByUserId(userId: string) {
    return this.orders
      .filter((o) => o.userId === userId)
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  }

  findAddressesByUserId(userId: string) {
    return this.addresses.filter((a) => a.userId === userId);
  }
}

export const db = new Database();
